#!/bin/bash --login
set -e
oldrev=$1
newrev=$2

run() {
  [ -x $1 ] && $1 $oldrev $newrev
}

echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)

umask 002

git submodule sync && git submodule update --init --recursive

# Install dependencies
source ~/.rbenvrc

rbenv install --keep --skip-existing `cat .ruby-version`
gem install bundler
rbenv rehash
bundler install --deployment --binstubs ./bin

# configure database credentials
cp -v ~/.database_credentials ./config/

# configure newrelic license key
sed -i "s/license_key:.*$/license_key: $(cat ~/.newrelic_license)/" config/newrelic.yml

bin/whenever --update-crontab

run deploy/before_restart
run deploy/restart && run deploy/after_restart

