#!/bin/sh

if pgrep -f bitcoinppi-app; then
  command="--onebyone restart"
else
  command=start
fi

export RACK_ENV=production
echo "restarting Thin"
./bin/thin --tag bitcoinppi-app --servers 4 --environment production --socket /var/tmp/bitcoinppi.sock --pid tmp/thin.pid --log log/thin.log --daemonize $command

echo "purging landingpage cache"
curl -XPURGE -H'Host: bitcoinppi.com' http://127.0.0.1/

