#!/bin/sh

if pgrep -f thin; then
  command=restart
else
  command=start
fi

export RACK_ENV=production
echo "restarting Thin"
./bin/thin --servers 4 --environment production --socket /var/tmp/bitcoinppi.sock --pid tmp/thin.pid --log log/thin.log --daemonize $command

