versions:
  - "1.1"
pages:
  api: API Documentation
meta_descriptions:
  /: The bitcoin purchasing power index (bitcoinppi) tells you how many Big Mac hamburgers you can buy with one bitcoin.
  /pages/api: Access the bitcoin purchasing power index public endpoints that return bitcoinppi data in JSON or CSV format.
currencies:
  - CNY
  - INR
  - USD
  - NOK
  - EUR
  - HKD
  - JPY
  - EUR
  - CAD
  - EUR
  - AUD
  - GBP
  - EUR
  - SEK
  - EUR
  - DKK
  - EUR
  - IDR
  - RUB
  - EUR
  - BRL
  - EUR
  - EUR
  - NZD
  - ILS
  - MXN
  - CZK
  - PLN
  - TRY
  - PKR
  - MYR
  - EUR
  - EUR
  - EUR
  - EUR
  - CLP
  - ARS
  - THB
  - ZAR
  - PHP
  - COP

