versions:
  - "1.1"
pages:
  api: API Documentation
currencies:
  - CNY
  - INR
  - USD
  - NOK
  - EUR
  - HKD
  - JPY
  - EUR
  - CAD
  - EUR
  - AUD
  - GBP
  - EUR
  - SEK
  - EUR
  - DKK
  - EUR
  - IDR
  - RUB
  - EUR
  - BRL
  - EUR
  - EUR
  - NZD
  - ILS
  - MXN
  - CZK
  - PLN
  - TRY
  - PKR
  - MYR
  - EUR
  - EUR
  - EUR
  - EUR
  - CLP
  - ARS
  - THB
  - ZAR
  - PHP
  - COP

