versions:
  - "1.1"
pages:
  api: API Documentation
meta_descriptions:
  /: The bitcoin purchasing power index (bitcoinppi) tells you how many Big Mac hamburgers you can buy with one bitcoin.
  /pages/api: Access the bitcoin purchasing power index public endpoints that return bitcoinppi data in JSON or CSV format.
currencies:
  - ARS
  - AUD
  - BRL
  - CAD
  - CHF
  - CLP
  - CNY
  - COP
  - CZK
  - DKK
  - EUR
  - GBP
  - HKD
  - IDR
  - ILS
  - INR
  - JPY
  - MXN
  - MYR
  - NOK
  - NZD
  - PHP
  - PKR
  - PLN
  - RUB
  - SEK
  - THB
  - TRY
  - USD
  - ZAR

